# file: .air.toml

root = "../../"
tmp_dir = "./cmd/server/bin"

[build]
  bin = "./bin/main"
  cmd = "su - rasjonell -c \"cd /home/rasjonell/Projects/hybr/cmd/server && templ generate && npm run build\" && go build -o ./bin/main ."
  delay = 500
  exclude_dir = ["./cmd/server/static", "./cmd/server/node_modules"]
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true

# Enable live-reloading on the browser.
[proxy]
  enabled = true
  app_port = 8080
  proxy_port = 8090
